apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: api-gateway
    app.kubernetes.io/instance: api-gateway-instance
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: kubectl
  name: api-gateway-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - image: 597088043946.dkr.ecr.ap-south-1.amazonaws.com/api-gateway:latest
          imagePullPolicy: Always
          name: api-gateway
          ports:
            - containerPort: 8000
